"""Remove UniqueConstraint by user_id from refresh_tokens

Revision ID: 02f7160c9038
Revises: d6a6bac0768e
Create Date: 2026-08-12 19:39:55.675413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f7160c9038'
down_revision: Union[str, Sequence[str], None] = 'd6a6bac0768e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
