"""Update tables associated with movie rating

Revision ID: 0496ab0c63be
Revises: 590d4dfbc0f7
Create Date: 2026-10-01 10:37:55.611505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0496ab0c63be'
down_revision: Union[str, Sequence[str], None] = '590d4dfbc0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'profile_id', name='favorite_movies_movie_id_profile_id_unique')
    )
    op.create_index(op.f('ix_favorite_movies_id'), 'favorite_movies', ['id'], unique=False)
    op.alter_column('comment_likes', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('comment_likes_comment_id_profile_id_key'), 'comment_likes', type_='unique')
    op.create_unique_constraint('comment_likes_comment_id_profile_id_unique', 'comment_likes', ['comment_id', 'profile_id'])
    op.create_foreign_key(None, 'comment_likes', 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment_likes', 'updated_at')
    op.add_column('comment_replies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('comment_replies', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment_replies', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_comment_replies_id'), 'comment_replies', ['id'], unique=False)
    op.add_column('movie_comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('movie_comments', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_comments', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_movie_comments_id'), 'movie_comments', ['id'], unique=False)
    op.add_column('movie_likes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('movie_likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_likes', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('movie_likes_movie_id_profile_id_key'), 'movie_likes', type_='unique')
    op.create_index(op.f('ix_movie_likes_id'), 'movie_likes', ['id'], unique=False)
    op.create_unique_constraint('movie_likes_movie_id_profile_id_unique', 'movie_likes', ['movie_id', 'profile_id'])
    op.alter_column('movie_rates', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_rates', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('movie_rates_movie_id_profile_id_key'), 'movie_rates', type_='unique')
    op.create_index(op.f('ix_movie_rates_id'), 'movie_rates', ['id'], unique=False)
    op.create_unique_constraint('movie_rates_movie_id_profile_id_unique', 'movie_rates', ['movie_id', 'profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_rates_movie_id_profile_id_unique', 'movie_rates', type_='unique')
    op.drop_index(op.f('ix_movie_rates_id'), table_name='movie_rates')
    op.create_unique_constraint(op.f('movie_rates_movie_id_profile_id_key'), 'movie_rates', ['movie_id', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('movie_rates', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_rates', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('movie_likes_movie_id_profile_id_unique', 'movie_likes', type_='unique')
    op.drop_index(op.f('ix_movie_likes_id'), table_name='movie_likes')
    op.create_unique_constraint(op.f('movie_likes_movie_id_profile_id_key'), 'movie_likes', ['movie_id', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('movie_likes', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('movie_likes', 'created_at')
    op.drop_index(op.f('ix_movie_comments_id'), table_name='movie_comments')
    op.alter_column('movie_comments', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_comments', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('movie_comments', 'created_at')
    op.drop_index(op.f('ix_comment_replies_id'), table_name='comment_replies')
    op.alter_column('comment_replies', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment_replies', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comment_replies', 'created_at')
    op.add_column('comment_likes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.drop_constraint('comment_likes_comment_id_profile_id_unique', 'comment_likes', type_='unique')
    op.create_unique_constraint(op.f('comment_likes_comment_id_profile_id_key'), 'comment_likes', ['comment_id', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('comment_likes', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_favorite_movies_id'), table_name='favorite_movies')
    op.drop_table('favorite_movies')
    # ### end Alembic commands ###
