"""Add columns date_of_birth and info to user_profiles

Revision ID: 04ad94bc6c17
Revises: 88b9c3ff84be
Create Date: 2026-08-12 15:37:59.878391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ad94bc6c17'
down_revision: Union[str, Sequence[str], None] = '88b9c3ff84be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('info', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'info')
    op.drop_column('user_profiles', 'date_of_birth')
    # ### end Alembic commands ###
