"""Rename genre_id on star_id to table movie_stars

Revision ID: 361460b2178d
Revises: 6cb877f8edee
Create Date: 2026-09-18 16:53:47.355826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361460b2178d'
down_revision: Union[str, Sequence[str], None] = '6cb877f8edee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_stars', sa.Column('star_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('movie_stars_genre_id_fkey'), 'movie_stars', type_='foreignkey')
    op.create_foreign_key(None, 'movie_stars', 'stars', ['star_id'], ['id'])
    op.drop_column('movie_stars', 'genre_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_stars', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movie_stars', type_='foreignkey')
    op.create_foreign_key(op.f('movie_stars_genre_id_fkey'), 'movie_stars', 'stars', ['genre_id'], ['id'])
    op.drop_column('movie_stars', 'star_id')
    # ### end Alembic commands ###
