"""Update column uuid of table movie

Revision ID: 6cb877f8edee
Revises: 8c0176bcaf6e
Create Date: 2026-09-10 07:38:24.543359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb877f8edee'
down_revision: Union[str, Sequence[str], None] = '8c0176bcaf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
